package ru.wolf.api.loadcurve;
import lombok.RequiredArgsConstructor; import org.springframework.http.ResponseEntity; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import ru.wolf.api.loadcurve.dto.*; import ru.wolf.api.project.*; import ru.wolf.api.routine.*; import ru.wolf.api.user.*; import java.time.*; import java.time.temporal.TemporalAdjusters; import java.util.*;
@Service @RequiredArgsConstructor public class LoadCurveService {
 private final LoadCurveEntryRepository entries; private final UserRepository users; private final ProjectRepository projects; private final RoutineRepository routines;
 @Transactional(readOnly=true) public List<LoadCurveResponse> project(String name,Long id){User u=current(name); Project p=projects.findByUserAndId(u,id).orElseThrow(); return entries.findByProjectIdOrderByWeekStart(p.getId()).stream().map(this::response).toList();}
 @Transactional(readOnly=true) public List<LoadCurveResponse> routine(String name,Long id){User u=current(name); Routine r=routines.findByUserAndId(u,id).orElseThrow(); return entries.findByRoutineIdOrderByWeekStart(r.getId()).stream().map(this::response).toList();}
 @Transactional public LoadCurveResponse putProject(String name,Long id,LoadCurveRequest req){User u=current(name); return save(req,projects.findByUserAndId(u,id).orElseThrow(),null);}
 @Transactional public LoadCurveResponse putRoutine(String name,Long id,LoadCurveRequest req){User u=current(name); return save(req,null,routines.findByUserAndId(u,id).orElseThrow());}
 @Transactional public ResponseEntity<Void> deleteProject(String name,Long id,Long entryId){User u=current(name); projects.findByUserAndId(u,id).orElseThrow(); LoadCurveEntry e=entries.findById(entryId).filter(x->x.getProject()!=null&&x.getProject().getId().equals(id)).orElseThrow(); entries.delete(e); return ResponseEntity.noContent().build();}
 @Transactional public ResponseEntity<Void> deleteRoutine(String name,Long id,Long entryId){User u=current(name); routines.findByUserAndId(u,id).orElseThrow(); LoadCurveEntry e=entries.findById(entryId).filter(x->x.getRoutine()!=null&&x.getRoutine().getId().equals(id)).orElseThrow(); entries.delete(e); return ResponseEntity.noContent().build();}
 private LoadCurveResponse save(LoadCurveRequest req,Project p,Routine r){LocalDate week=req.weekStart().with(TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY)); LocalDate end=req.endWeek()==null?week:req.endWeek().with(TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY)); if(end.isBefore(week)) throw new IllegalArgumentException("Конец сегмента не может быть раньше начала"); List<LoadCurveEntry> owned=p!=null?entries.findByProjectIdOrderByWeekStart(p.getId()):entries.findByRoutineIdOrderByWeekStart(r.getId()); if(!end.equals(week)&&owned.stream().anyMatch(x->!x.getWeekStart().isBefore(week)&&!x.getWeekStart().isAfter(end))) throw new IllegalArgumentException("Интервалы кривой не должны пересекаться"); LoadCurveEntry first=null; for(LocalDate c=week;!c.isAfter(end);c=c.plusWeeks(1)){LocalDate current=c; LoadCurveEntry e=owned.stream().filter(x->x.getWeekStart().equals(current)).findFirst().orElseGet(()->LoadCurveEntry.builder().project(p).routine(r).weekStart(current).build()); e.setHours(req.hours().setScale(2)); LoadCurveEntry saved=entries.save(e); if(first==null)first=saved;} return response(first);}
 private User current(String n){return users.findByUsername(n).orElseThrow();} private LoadCurveResponse response(LoadCurveEntry e){return new LoadCurveResponse(e.getId(),e.getWeekStart(),e.getHours(),e.getProject()!=null?"project":"routine");}
}
